---
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

# an old handler that I no longer believe is necessary
# will remove if it is confirmed useless (Feb 2021)
#- name: reboot server
#  command: "/sbin/shutdown -r +1"
#  ignore_errors: true